apps/clientes/urls.py
from django.conf.urls import url
from apps.clientes import views

urlpatterns = [
    url(r'^lista_clientes/$', views.listaClientes, name='lista_clientes'),
    url(r'^crear_cliente/$', views.nuevoCliente, name='crear_cliente'),
    url(r'^ver_cliente/(?P<cliente_id>\d+)/$', views.verCliente, name='ver_cliente'),
    url(r'^editar_cliente/(?P<cliente_id>\d+)/$', views.editarCliente, name='editar_cliente'),
    url(r'^eliminar_cliente/(?P<cliente_id>\d+)/$', views.eliminarCliente, name='eliminar_cliente'),
]

gestionFarmacia/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('apps.clientes.urls', namespace='clientes_url')),
]

apps/clientes/models.py
from django.db import models


class Cliente(models.Model):
    dni = models.IntegerField(unique=True)
    nombre = models.CharField(max_length=600)
    apellidos = models.CharField(max_length=100)
    direccion = models.CharField(max_length=100)
    telefono = models.IntegerField(verbose_name='Telefono')
    distrito = models.CharField(max_length=100)

    def __str__(self):
        return self.nombre



apps/clientes/views.py
from django.shortcuts import render
from apps.clientes.models import Cliente


def listaClientes(request):
    clientes = Cliente.objects.all()
    return render(request, 'clientes/lista_clientes.html', {'listaClientes': clientes})


def nuevoCliente(request):
    pass


def verCliente(request):
    pass


def editarCliente(request):
    pass


def eliminarCliente(request):
    pass







templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}{% endblock %}</title>
</head>
<body>
    <div id="content">
        {% block content %}{% endblock %}
    </div>
</body>
</html>

templates/clientes/lista_clientes.html
{% extends "base.html" %}
{% block title %} Lista de Clientes {% endblock %}
{% block content %}
    <h5><a href="{% url 'clientes_url:crear_cliente' %}">Nuevo Cliente</a></h5>

    <table border="1">
        <thead>
            <th>N°</th>
            <th>DNI</th>
            <th>NOMBRES COMPLETO</th>
            <th>APELLIDOS COMPLETO</th>
            <th>DIRECCION</th>
            <th>TELEFONO DEL CLIENTE</th>
            <th colspan="3">ACCIONES</th>
	    <th>DISTRITO</th>
	    <th>PRIMERA FILA</th>
	    <th>SEGUNDA FILA</th>
	    <th>TERCERA FILA</th>
	    <th>CUARTA FILA</th>
	    <th>QUINTA FILA</th>
        </thead>
        <tbody>
            {% for cliente in listaClientes%}
                <tr>
                    <td>{{ forloop.counter }}</td>
                    <td>{{ cliente.dni }}</td>
                    <td>{{ cliente.nombre }}</td>
                    <td>{{ cliente.apellidos }}</td>
                    <td>{{ cliente.direccion }}</td>
                    <td>{{ cliente.telefono }}</td>
                    <td><a href="{%url 'clientes_url:ver_cliente' cliente.id %}">Ver Cliente</a></td>
                    <td><a href="{%url 'clientes_url:editar_cliente' cliente.id %}">Editar</a></td>
                    <td><a href="{%url 'clientes_url:eliminar_cliente' cliente.id %}">Eliminar</a></td>
		    <td>DISTRITO</td>
		    <td>FILA 1</td>
		    <td>FILA 2</td>
		    <td>FILA 3</td>
		    <th>FILA 4</th>
	    	    <th>FILA 5</th>
                </tr>
            {% endfor %}
        </tbody>
    </table>

{% endblock %}